import asyncio
import json
import re

from langchain_core.messages import HumanMessage
from langchain_core.tools import tool

from ppt_agent.agent.state import SessionState, PipelineStep, sync_session_index
from ppt_agent.config import get_session_dir, settings
from ppt_agent.llm import get_model
from ppt_agent.progress import get_queue
from ppt_agent.prompts.slide import (
    SLIDE_PROMPT,
    CONTENT_FULL_PAGE_PROMPT,
    _component_styles_section,
    _emphasis_section,
)
from ppt_agent.templates.registry import load_skeleton, render_skeleton

_CODE_FENCE = re.compile(r"```(?:html)?\s*(.*?)\s*```", re.DOTALL)


def _strip_code_fence(text: str) -> str:
    match = _CODE_FENCE.search(text)
    if match:
        return match.group(1).strip()
    return text.strip()


def _is_valid_html(text: str) -> bool:
    lower = text.lower()
    return "<html" in lower or "<body" in lower or "<div" in lower


def _inject_template_vars(html: str, style_spec: dict) -> str:
    """Inject :root CSS variables and overflow safety net into the generated HTML."""
    colors = style_spec.get("colors", {})
    typo = style_spec.get("typography", {})
    default_font = "'Microsoft YaHei', sans-serif"
    tf = typo.get("title_font", default_font)
    bf = typo.get("body_font", tf)
    lines = [
        f"  --primary: {colors.get('primary', '#1a365d')};",
        f"  --secondary: {colors.get('secondary', '#2b6cb0')};",
        f"  --accent: {colors.get('accent', '#ed8936')};",
        f"  --accent-2: {colors.get('accent_2', colors.get('accent', '#ed8936'))};",
        f"  --bg: {colors.get('background', '#ffffff')};",
        f"  --card-bg: {colors.get('card_bg', colors.get('background', '#ffffff'))};",
        f"  --text: {colors.get('text', '#2d3748')};",
        f"  --text-light: {colors.get('text_light', '#718096')};",
        f"  --border: {colors.get('border', '#e2e8f0')};",
        f"  --title-font: {tf};",
        f"  --body-font: {bf};",
    ]
    var_block = "<style>:root {\n" + "\n".join(lines) + "\n}</style>"
    # Overflow safety net: ensure body and first child container stay within 720px
    safety_css = (
        "<style>\n"
        "body, .slide, .slide-container { "
        "max-height:720px!important; overflow:hidden!important; }\n"
        "</style>"
    )
    return html.replace("</head>", f"{var_block}\n{safety_css}\n</head>")


def _validate_content_html(html: str, headline: str) -> bool:
    """Validate a full-page HTML generated by the LLM."""
    checks = [
        "<html" in html and "</html>" in html,
        "<body" in html,
        "1280" in html and "720" in html,
        "overflow:hidden" in html or "overflow: hidden" in html,
        headline[:20] in html if headline else True,
        "var(--" in html,
        "<script" not in html.lower(),
    ]
    return all(checks)


async def _generate_one_slide(
    sem: asyncio.Semaphore,
    model,
    slide_info: dict,
    total: int,
    style_spec: dict,
    template_key: str,
) -> tuple[dict, str]:
    layout = slide_info["layout"]
    if layout in ("content", "toc"):
        return await _generate_full_page(sem, model, slide_info, total, style_spec, template_key)
    return await _generate_with_skeleton(sem, model, slide_info, total, style_spec, template_key)


def _build_style_sections(style_spec: dict, layout: str) -> tuple[str, str]:
    component_styles = style_spec.get("component_styles", {})
    layout_style = component_styles.get(layout, "")
    emphasis = style_spec.get("emphasis", {})
    return _component_styles_section(layout_style), _emphasis_section(emphasis)


async def _generate_with_skeleton(
    sem: asyncio.Semaphore,
    model,
    slide_info: dict,
    total: int,
    style_spec: dict,
    template_key: str,
) -> tuple[dict, str]:
    """Generate slide using skeleton template (cover/section/ending)."""
    async with sem:
        layout = slide_info["layout"]
        headline = slide_info.get("headline", "")
        page = slide_info["page"]

        skeleton = load_skeleton(layout, template_key)
        comp_section, emp_section = _build_style_sections(style_spec, layout)

        prompt = SLIDE_PROMPT.format(
            page=page,
            total=total,
            layout=layout,
            headline=headline,
            body_text=slide_info.get("body_text", ""),
            supporting_points=json.dumps(
                slide_info.get("supporting_points", []), ensure_ascii=False
            ),
            speaker_notes=slide_info.get("speaker_notes", ""),
            section=slide_info.get("section", ""),
            visual_hint=slide_info.get("visual_hint", ""),
            component_styles_section=comp_section,
            emphasis_section=emp_section,
        )
        response = await model.ainvoke([HumanMessage(content=prompt)])
        content_html = _strip_code_fence(response.content)

        full_html = render_skeleton(
            skeleton_html=skeleton,
            style_spec=style_spec,
            headline=headline,
            page=page,
            total=total,
            content=content_html,
            speaker_notes=slide_info.get("speaker_notes", ""),
        )
        return slide_info, full_html


_MAX_FULL_PAGE_RETRIES = 2


async def _generate_full_page(
    sem: asyncio.Semaphore,
    model,
    slide_info: dict,
    total: int,
    style_spec: dict,
    template_key: str,
) -> tuple[dict, str]:
    """Generate content/toc slides as full HTML pages with validation + skeleton fallback."""
    async with sem:
        layout = slide_info["layout"]
        headline = slide_info.get("headline", "")
        page = slide_info["page"]
        comp_section, emp_section = _build_style_sections(style_spec, layout)

        prompt = CONTENT_FULL_PAGE_PROMPT.format(
            page=page,
            total=total,
            layout=layout,
            headline=headline,
            body_text=slide_info.get("body_text", ""),
            supporting_points=json.dumps(
                slide_info.get("supporting_points", []), ensure_ascii=False
            ),
            speaker_notes=slide_info.get("speaker_notes", ""),
            section=slide_info.get("section", ""),
            visual_hint=slide_info.get("visual_hint", ""),
            component_styles_section=comp_section,
            emphasis_section=emp_section,
        )
        messages = [HumanMessage(content=prompt)]
        hint = "生成的 HTML 不满足结构要求。请确保：完整 HTML 页面、body 1280×720 overflow:hidden、内容不超出 720px 高度（这是最高优先级）、包含页码、headline 醒目呈现、使用 var(--xxx) 引用颜色、内容模块不超过 3 个。重新输出。"

        for attempt in range(_MAX_FULL_PAGE_RETRIES):
            response = await model.ainvoke(messages)
            full_html = _strip_code_fence(response.content)

            if "</head>" not in full_html:
                full_html = full_html.replace("<html", "<html\n<head></head>", 1) if "<html" in full_html else full_html
            full_html = _inject_template_vars(full_html, style_spec)

            if _validate_content_html(full_html, headline):
                return slide_info, full_html

            messages.append(response)
            messages.append(HumanMessage(content=hint))

        # All retries failed — fallback to skeleton
        skeleton = load_skeleton(layout, template_key)
        fragment_prompt = SLIDE_PROMPT.format(
            page=page,
            total=total,
            layout=layout,
            headline=headline,
            body_text=slide_info.get("body_text", ""),
            supporting_points=json.dumps(
                slide_info.get("supporting_points", []), ensure_ascii=False
            ),
            speaker_notes=slide_info.get("speaker_notes", ""),
            section=slide_info.get("section", ""),
            visual_hint=slide_info.get("visual_hint", ""),
            component_styles_section=comp_section,
            emphasis_section=emp_section,
        )
        frag_response = await model.ainvoke([HumanMessage(content=fragment_prompt)])
        content_html = _strip_code_fence(frag_response.content)
        full_html = render_skeleton(
            skeleton_html=skeleton,
            style_spec=style_spec,
            headline=headline,
            page=page,
            total=total,
            content=content_html,
            speaker_notes=slide_info.get("speaker_notes", ""),
        )
        return slide_info, full_html


async def _safe_generate_one(
    slide, sem, model, total, style_spec, template_key
):
    """Wrapper that catches exceptions from _generate_one_slide."""
    try:
        info, html = await _generate_one_slide(
            sem, model, slide, total, style_spec, template_key
        )
        return info, html, None
    except Exception as e:
        return slide, None, str(e)


@tool
async def generate_slides() -> str:
    """根据大纲和风格规范并发生成所有 HTML 幻灯片。

    自动读取 outline.json 和 style_spec.json，并发调用 LLM 生成每页 HTML。
    """
    session_dir = get_session_dir()
    outline_path = session_dir / "outline.json"
    style_spec_path = session_dir / "style_spec.json"

    if not outline_path.exists():
        return "[错误] outline.json 不存在，请先生成大纲。"
    if not style_spec_path.exists():
        return "[错误] style_spec.json 不存在，请先选择模板。"

    with open(outline_path, "r", encoding="utf-8") as f:
        outline = json.load(f)
    with open(style_spec_path, "r", encoding="utf-8") as f:
        style_spec = json.load(f)

    # Load template_key from session state
    state = SessionState.load(session_dir / "session.json")
    template_key = state.template_key or ""

    slides = outline["slides"]
    total = len(slides)
    model = get_model()
    sem = asyncio.Semaphore(settings.slide_concurrency)

    slides_dir = session_dir / "slides"
    slides_dir.mkdir(parents=True, exist_ok=True)

    session_id = session_dir.name
    queue = get_queue(session_id)

    tasks = [
        _safe_generate_one(s, sem, model, total, style_spec, template_key)
        for s in slides
    ]

    generated = []
    failed = []
    for coro in asyncio.as_completed(tasks):
        slide_info, html_content, error = await coro

        if error:
            page_num = slide_info.get("page", "?")
            failed.append(f"第 {page_num} 页: {error}")
            if queue:
                await queue.put(
                    {"type": "slide_error", "page": page_num, "error": error}
                )
            continue

        if not html_content or not _is_valid_html(html_content):
            failed.append(f"第 {slide_info['page']} 页: 生成的 HTML 内容无效")
            if queue:
                await queue.put(
                    {
                        "type": "slide_error",
                        "page": slide_info["page"],
                        "error": "HTML 无效",
                    }
                )
            continue

        filename = f"slide_{slide_info['page']:02d}_{slide_info['layout']}.html"
        filepath = slides_dir / filename
        filepath.write_text(html_content, encoding="utf-8")
        generated.append(str(filepath))

        if queue:
            await queue.put(
                {
                    "type": "slide_generated",
                    "page": slide_info["page"],
                    "layout": slide_info["layout"],
                    "filename": filename,
                    "total": total,
                }
            )

    state = SessionState.load(session_dir / "session.json")
    state.step = PipelineStep.SLIDES_DONE
    state.slides_dir = str(slides_dir)
    state.save(session_dir / "session.json")
    sync_session_index(state.session_id, step=state.step.value)

    msg = f"已生成 {len(generated)} 张幻灯片:\n" + "\n".join(generated)
    if failed:
        msg += f"\n\n[警告] {len(failed)} 张幻灯片生成失败:\n" + "\n".join(failed)
    return msg
